# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_expectation_W_Rcpp <- function(Z_samples, gamma) {
    .Call(`_rMMLEDirBer_compute_expectation_W_Rcpp`, Z_samples, gamma)
}

compute_expectation_H_dirdir_Rcpp <- function(C_samples, gamma) {
    .Call(`_rMMLEDirBer_compute_expectation_H_dirdir_Rcpp`, C_samples, gamma)
}

compute_expectation_H_Rcpp <- function(Z_samples, V, alpha, beta) {
    .Call(`_rMMLEDirBer_compute_expectation_H_Rcpp`, Z_samples, V, alpha, beta)
}

Gibbs_DirBer_DP_Rcpp <- function(V, Z, alpha = 1, beta = 1, gamma = 1, iter = 100L, burnin = 0.5) {
    .Call(`_rMMLEDirBer_Gibbs_DirBer_DP_Rcpp`, V, Z, alpha, beta, gamma, iter, burnin)
}

Gibbs_DirBer_finite_Rcpp <- function(V, Z, K, alpha = 1, beta = 1, gamma = 1, iter = 100L, burnin = 0.5) {
    .Call(`_rMMLEDirBer_Gibbs_DirBer_finite_Rcpp`, V, Z, K, alpha, beta, gamma, iter, burnin)
}

Gibbs_DirDir_finite_Rcpp <- function(V, Z, K, alpha = 1, gamma = 1, iter = 100L, burnin = 0.5) {
    .Call(`_rMMLEDirBer_Gibbs_DirDir_finite_Rcpp`, V, Z, K, alpha, gamma, iter, burnin)
}

samples_VWH_DirBer <- function(V, Z_samples, gamma, alpha, beta) {
    .Call(`_rMMLEDirBer_samples_VWH_DirBer`, V, Z_samples, gamma, alpha, beta)
}

VB_DirBer_Rcpp <- function(V, Z, K, alpha = 1, beta = 1, gamma = 1, iter = 100L) {
    .Call(`_rMMLEDirBer_VB_DirBer_Rcpp`, V, Z, K, alpha, beta, gamma, iter)
}

E_log_p_W_Rcpp <- function(E_log_W, gamma) {
    .Call(`_rMMLEDirBer_E_log_p_W_Rcpp`, E_log_W, gamma)
}

E_log_q_W_Rcpp <- function(E_log_W, gamma_vb) {
    .Call(`_rMMLEDirBer_E_log_q_W_Rcpp`, E_log_W, gamma_vb)
}

E_log_p_Z_Rcpp <- function(E_Z, E_log_W, V) {
    .Call(`_rMMLEDirBer_E_log_p_Z_Rcpp`, E_Z, E_log_W, V)
}

E_log_q_Z_Rcpp <- function(E_Z, V) {
    .Call(`_rMMLEDirBer_E_log_q_Z_Rcpp`, E_Z, V)
}

E_log_p_H_Rcpp <- function(E_log_H, E_log_1_H, alpha, beta) {
    .Call(`_rMMLEDirBer_E_log_p_H_Rcpp`, E_log_H, E_log_1_H, alpha, beta)
}

E_log_q_H_Rcpp <- function(E_log_H, E_log_1_H, alpha_vb, beta_vb) {
    .Call(`_rMMLEDirBer_E_log_q_H_Rcpp`, E_log_H, E_log_1_H, alpha_vb, beta_vb)
}

E_log_p_V_Rcpp <- function(V, E_Z, E_log_H, E_log_1_H) {
    .Call(`_rMMLEDirBer_E_log_p_V_Rcpp`, V, E_Z, E_log_H, E_log_1_H)
}

likelihood_aspect <- function(V, gamma_vb, alpha_vb, beta_vb) {
    .Call(`_rMMLEDirBer_likelihood_aspect`, V, gamma_vb, alpha_vb, beta_vb)
}

lower_bound_aspect <- function(E_Z, E_log_W, E_log_H, E_log_1_H, gamma_vb, alpha_vb, beta_vb, alpha, beta, gamma, V) {
    .Call(`_rMMLEDirBer_lower_bound_aspect`, E_Z, E_log_W, E_log_H, E_log_1_H, gamma_vb, alpha_vb, beta_vb, alpha, beta, gamma, V)
}

VB_Aspect_Rcpp <- function(V, Z, K, alpha = 1, beta = 1, gamma = 1, iter = 100L, checklb = FALSE) {
    .Call(`_rMMLEDirBer_VB_Aspect_Rcpp`, V, Z, K, alpha, beta, gamma, iter, checklb)
}

matrix_to_tensor_R <- function(Z, Kmax) {
    .Call(`_rMMLEDirBer_matrix_to_tensor_R`, Z, Kmax)
}

printVecs <- function(v1, v2, K) {
    invisible(.Call(`_rMMLEDirBer_printVecs`, v1, v2, K))
}

sample_gibbs_cpp <- function(v_n, W, C, alpha = 1, iter = 100L, burnin = 0.5) {
    .Call(`_rMMLEDirBer_sample_gibbs_cpp`, v_n, W, C, alpha, iter, burnin)
}

